package cli

import (
	"bytes"
	"context"
	"crypto/sha256"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"reflect"
	"strconv"
	"strings"
	"testing"

	"github.com/bjornarhagen/saga-rydd/internal/config"
	"github.com/bjornarhagen/saga-rydd/internal/inventory"
	"golang.org/x/sys/unix"
)

// This acceptance fixture uses only generated files. Every inventory row,
// original observation and fresh observation is produced by the public CLI;
// none of the expected digests or roles comes from authored database rows.
func duplicateGateFixture(t *testing.T, names []string, create func(string)) (*hashProposalCLIFixture, inventory.HashProposal) {
	t.Helper()
	canonical := func() string {
		p, err := filepath.EvalSymlinks(t.TempDir())
		if err != nil {
			t.Fatal(err)
		}
		return p
	}
	f := &hashProposalCLIFixture{t: t, base: filepath.Join(canonical(), "private state"), root: canonical(), report: filepath.Join(canonical(), "saved report.json")}
	parent := filepath.Join(f.root, "generated\n雪")
	if err := os.Mkdir(parent, 0700); err != nil {
		t.Fatal(err)
	}
	create(parent)
	paths, err := config.ResolvePaths(f.base)
	if err != nil {
		t.Fatal(err)
	}
	f.source = manualState(paths, f.root)
	p := hashKeeperRescanAndSelect(t, f, names)
	if f.page.ContentVerified || f.page.CurrentStateVerified || f.page.EstimatedReclaimableBytes != nil || f.page.NextCursor != "" || len(p.Targets) != len(names) {
		t.Fatal("same-size discovery claimed content, savings or incomplete fixture scope", f.page)
	}
	for i, target := range p.Targets {
		if !bytes.Equal(target.File.PathBytes, []byte(filepath.Join(parent, names[i]))) {
			t.Fatal("production selection lost exact caller path order", i, target.File.PathBytes)
		}
	}
	return f, p
}

func duplicateGateWrite(t *testing.T, parent, name string, body []byte) {
	t.Helper()
	if err := os.WriteFile(filepath.Join(parent, name), body, 0600); err != nil {
		t.Fatal(err)
	}
}

// The equal-size generated fixtures have a fixed, explicit number of calls.
// No refusal, uncertainty or incomplete observation is retried by this helper.
func duplicateGateOriginalHashes(t *testing.T, f *hashProposalCLIFixture, p inventory.HashProposal, expected [][]byte) (HashReport, string, inventory.HashGroupsReport, string) {
	t.Helper()
	ctx := context.Background()
	var total int64
	for _, body := range expected {
		total += int64(len(body))
	}
	code, raw, diagnostic := f.run(ctx, hashReadApproveArgs(p.SelectionID, total, total)...)
	c := hashCLIConsentResult(t, code, raw, diagnostic, "approve")
	if c.Approval.DailyReservedByteLimit != total || c.Approval.LifetimeReservedByteLimit != total {
		t.Fatal("original scope changed exact generated byte caps", raw)
	}
	rounds := (int64(len(expected[0])) + inventory.FileHashStepByteLimit - 1) / inventory.FileHashStepByteLimit
	var charged int64
	for round := int64(0); round < rounds; round++ {
		for i, body := range expected {
			code, raw, diagnostic = f.run(ctx, "hash", "--run", c.ID, "--json")
			r := hashCLIStepResult(t, code, raw, diagnostic).Result
			from := round * inventory.FileHashStepByteLimit
			grant := min(inventory.FileHashStepByteLimit, int64(len(body))-from)
			wantOffset := from + grant
			if r.WorkID != strconv.Itoa(i+1) || r.ReservedBytes != grant || r.Usage.RequestedBytes != grant || r.Usage.ReadBytes != grant || r.DurableOffset != wantOffset || !bytes.Equal(r.Progress.PathBytes, p.Targets[i].File.PathBytes) {
				t.Fatal("original finite run lost exact scope, fair order or accounting", raw)
			}
			if wantOffset == int64(len(body)) {
				if r.Status != "hash_observed" || r.Progress.SHA256 != fmt.Sprintf("%x", sha256.Sum256(body)) {
					t.Fatal("full observation differs from independently known generated bytes", raw)
				}
			} else if r.Status != "pending" || r.Progress.SHA256 != "" {
				t.Fatal("partial original read exposed a full digest", raw)
			}
			charged += grant
			if r.Budget == nil || r.Budget.TotalReservedBytes != charged || r.Budget.TotalReadBytes != charged || r.Budget.TotalUnknownReservedBytes != 0 {
				t.Fatal("original byte accounting differs from generated reads", raw)
			}
		}
	}
	code, snapshotRaw, diagnostic := f.run(ctx, "hashes", "--json")
	snapshot := hashCLIReport(t, code, snapshotRaw, diagnostic)
	code, groupsRaw, diagnostic := f.run(ctx, "hashes", "--groups", "--json")
	groups := hashGroupsCLIReport(t, code, groupsRaw, diagnostic)
	if len(snapshot.Work) != len(expected) || groups.SelectedWork != len(expected) || groups.CompletedObservations != len(expected) || groups.UnfinishedWork != 0 {
		t.Fatal("completed finite fixture has missing or added observations", snapshotRaw, groupsRaw)
	}
	for i, work := range snapshot.Work {
		if work.Status != "complete" || work.SHA256 != fmt.Sprintf("%x", sha256.Sum256(expected[i])) || work.DurableOffset != int64(len(expected[i])) {
			t.Fatal("saved original observation differs from independent bytes", work)
		}
	}
	return snapshot, snapshotRaw, groups, groupsRaw
}

func TestDuplicateGateCLIKnownGroupsExactRolesAndFreshAccounting(t *testing.T) {
	// A one-byte near miss has the same length and shares every other byte.
	equal := make([]byte, 4097)
	for i := range equal {
		equal[i] = byte((i*37 + i/11 + 19) % 251)
	}
	near := bytes.Clone(equal)
	near[len(near)/2] ^= 1
	names := []string{"near miss", "first copy", "keeper\"雪", "second copy", "unselected equal"}
	expected := [][]byte{near, equal, equal, equal, equal}
	f, p := duplicateGateFixture(t, names, func(parent string) {
		for i, name := range names {
			duplicateGateWrite(t, parent, name, expected[i])
		}
	})
	sourceBytes := hashCLIBytes(t, f.root, f.source)
	original, originalRaw, groups, groupsRaw := duplicateGateOriginalHashes(t, f, p, expected)
	if len(groups.Groups) != 1 || groups.UnmatchedCompletedObservations != 1 {
		t.Fatal("equal-size near miss was grouped as matching content", groupsRaw)
	}
	g := groups.Groups[0]
	if g.SHA256 != fmt.Sprintf("%x", sha256.Sum256(equal)) || g.LogicalBytes != int64(len(equal)) || g.SavedIdentities != 4 || g.RepeatedSavedPaths != 0 || g.ConflictingSavedIdentities != 0 || len(g.Members) != 4 {
		t.Fatal("known full-hash group differs from generated truth", groupsRaw)
	}
	for i, member := range g.Members {
		file := p.Targets[i+1].File
		if member.WorkID != strconv.Itoa(i+2) || member.FileID != file.ID || !bytes.Equal(member.PathBytes, file.PathBytes) || member.RepeatedSavedIdentity || member.SavedIdentityConflict {
			t.Fatal("matching group remapped or widened known members", member)
		}
	}
	choice := hashMetadataCLIChoice(t, f, p.SelectionID, "3", "4", "2")
	evidence := choice.Record.Evidence
	if evidence.Keeper.WorkID != "3" || len(evidence.Copies) != 2 || evidence.Copies[0].WorkID != "4" || evidence.Copies[1].WorkID != "2" || evidence.SelectedWork != 5 || evidence.UnmatchedCompletedObservations != 1 || !reflect.DeepEqual(evidence.Budget, original.Budget) {
		t.Fatal("explicit nonfirst keeper/subset/caller copy order changed", evidence)
	}
	ctx := context.Background()
	code, raw, diagnostic := f.run(ctx, "hash", "--new-job-key", "--json")
	var key struct {
		OK   bool                  `json:"ok"`
		Hash HashFreshJobKeyResult `json:"hash"`
	}
	if err := json.Unmarshal([]byte(raw), &key); err != nil || code != 0 || diagnostic != "" || !key.OK || !inventory.ValidHashFreshJobKey(key.Hash.JobKey) || key.Hash.Saved || key.Hash.ApprovalAvailable || key.Hash.Executable {
		t.Fatal("generated explicit job key has invalid authority", code, raw, diagnostic, err)
	}
	code, raw, diagnostic = f.run(ctx, "hash", "--save-choice-job", choice.ID, "--job-key", key.Hash.JobKey, "--json")
	job := hashFreshJobCLIReport(t, code, raw, diagnostic, "save").Job
	wantIDs := []string{"3", "4", "2"}
	if len(job.Record.Request.Targets) != len(wantIDs) || len(job.Work) != len(wantIDs) || !reflect.DeepEqual(job.Record.Request.HistoricalChoice, choice) {
		t.Fatal("fresh job widened the exact historical subset", raw)
	}
	for i, target := range job.Record.Request.Targets {
		old, _ := strconv.Atoi(wantIDs[i])
		wantRole := "copy"
		if i == 0 {
			wantRole = "keeper"
		}
		if target.Role != wantRole || target.Observation.WorkID != wantIDs[i] || !reflect.DeepEqual(target.Target, p.Targets[old-1]) || !bytes.Equal(target.Observation.PathBytes, p.Targets[old-1].File.PathBytes) {
			t.Fatal("fresh job remapped full frozen targets or added unselected rows", target)
		}
	}
	capBytes := int64(3 * len(equal))
	code, raw, diagnostic = f.run(ctx, "hash", "--approve-job", job.ID, "--confirm-content-read", "--max-day-bytes", strconv.FormatInt(capBytes, 10), "--max-total-bytes", strconv.FormatInt(capBytes, 10), "--json")
	c := hashFreshReadCLIReport(t, code, raw, diagnostic, "approve")
	if c.ID == original.ReadConsent.ID || c.Approval.JobID != job.ID || c.Approval.JobKey != job.Record.JobKey || c.Approval.RequestID != job.Record.Request.RequestID || c.Approval.DailyReservedByteLimit != capBytes || c.Approval.LifetimeReservedByteLimit != capBytes {
		t.Fatal("fresh scope reused original permission or changed caps", raw)
	}
	for i, id := range wantIDs {
		code, raw, diagnostic = f.run(ctx, "hash", "--run-job", c.ID, "--json")
		r := hashFreshRunCLIReport(t, code, raw, diagnostic).Result
		if r.JobID != job.ID || r.Ordinal != i+1 || r.HistoricalWorkID != id || r.Role != job.Work[i].Role || r.Status != "hash_observed" || r.Progress.SHA256 != g.SHA256 || !bytes.Equal(r.Progress.PathBytes, job.Record.Request.Targets[i].Target.File.PathBytes) || r.DurableOffset != int64(len(equal)) || r.ReservedBytes != int64(len(equal)) || r.Usage.ReadBytes != int64(len(equal)) || r.Usage.RequestedBytes != int64(len(equal)) || r.FreshBudget == nil || r.FreshBudget.TotalReadBytes != int64((i+1)*len(equal)) || r.FreshBudget.TotalUnknownReservedBytes != 0 {
			t.Fatal("fresh observation reused original progress or lost explicit roles/new accounting", raw)
		}
	}
	code, raw, diagnostic = f.run(ctx, "hash", "--show-job", job.ID, "--json")
	shown := hashFreshJobCLIReportWithProgress(t, code, raw, diagnostic, job)
	if shown.FreshReservedBytes != capBytes || shown.FreshRequestedBytes != capBytes || shown.FreshReadBytes != capBytes || len(shown.Progress) != 3 {
		t.Fatal("saved fresh counters differ from independently expected reads", raw)
	}
	for i, progress := range shown.Progress {
		if progress.Ordinal != i+1 || progress.HistoricalWorkID != wantIDs[i] || progress.Status != "complete" || progress.Sequence != 1 || progress.DurableOffset != int64(len(equal)) || progress.SHA256 != g.SHA256 {
			t.Fatal("fresh saved progress differs from explicit independent reads", progress)
		}
	}
	for _, report := range []struct {
		args []string
		want string
	}{{[]string{"hashes", "--json"}, originalRaw}, {[]string{"hashes", "--groups", "--json"}, groupsRaw}} {
		code, raw, diagnostic = f.run(ctx, report.args...)
		if code != 0 || diagnostic != "" || raw != report.want {
			t.Fatal("fresh reads changed original observations, consent, accounting or groups", code, raw, diagnostic)
		}
	}
	code, raw, diagnostic = f.run(ctx, "hashes", "--choice", choice.ID, "--json")
	if saved := hashChoiceCLIReport(t, code, raw, diagnostic, "hashes"); !reflect.DeepEqual(saved, choice) {
		t.Fatal("fresh reads refreshed the immutable historical choice", raw)
	}
	if !reflect.DeepEqual(sourceBytes, hashCLIBytes(t, f.root, f.source)) {
		t.Fatal("original/fresh reads changed generated source or inventory bytes")
	}
}

func TestDuplicateGateCLIRealSparseLogicalAndAllocatedEvidence(t *testing.T) {
	size := int(inventory.FileHashStepByteLimit) + 65
	zeros := make([]byte, size)
	near := bytes.Clone(zeros)
	near[size/2] = 1
	names := []string{"sparse hole", "dense zeros", "near miss"}
	var actual unix.Stat_t
	f, p := duplicateGateFixture(t, names, func(parent string) {
		path := filepath.Join(parent, names[0])
		file, err := os.OpenFile(path, os.O_CREATE|os.O_EXCL|os.O_WRONLY, 0600)
		if err != nil {
			t.Fatal(err)
		}
		if err = file.Truncate(int64(size)); err != nil {
			_ = file.Close()
			t.Fatal(err)
		}
		if err = file.Close(); err != nil {
			t.Fatal(err)
		}
		if err = unix.Stat(path, &actual); err != nil {
			t.Fatal(err)
		}
		// Truncate without writes creates a real hole. Allocation is checked
		// independently; unsupported fixture filesystems are not a passed gate.
		if actual.Blocks*512 >= int64(size) {
			t.Skip("fixture filesystem did not expose sparse allocation; native sparse acceptance remains unverified")
		}
		duplicateGateWrite(t, parent, names[1], zeros)
		duplicateGateWrite(t, parent, names[2], near)
	})
	if p.Targets[0].File.Size != int64(size) || p.Targets[0].File.Allocated != actual.Blocks*512 || p.Targets[0].File.Allocated >= p.Targets[0].File.Size {
		t.Fatal("saved sparse logical/allocated evidence differs from native metadata", p.Targets[0])
	}
	_, _, groups, raw := duplicateGateOriginalHashes(t, f, p, [][]byte{zeros, zeros, near})
	if groups.UnmatchedCompletedObservations != 1 || len(groups.Groups) != 1 || groups.Groups[0].LogicalBytes != int64(size) || groups.Groups[0].SHA256 != fmt.Sprintf("%x", sha256.Sum256(zeros)) || len(groups.Groups[0].Members) != 2 || groups.Groups[0].Members[0].WorkID != "1" || groups.Groups[0].Members[1].WorkID != "2" || groups.Groups[0].Members[0].SavedAllocatedBytes != actual.Blocks*512 {
		t.Fatal("sparse holes were not hashed as their logical zero contents", raw)
	}
	code, human, diagnostic := f.run(context.Background(), "report", "--same-size", "-d", f.root, "--min-size-bytes", "1")
	flat := strings.Join(strings.Fields(human), " ")
	for _, want := range []string{"SAME-SIZE FILES - CONTENT NOT CHECKED", "File size:", humanBytes(int64(size)), "Allocated on disk", humanBytes(actual.Blocks * 512), "There is no estimate of space you can free"} {
		if code != 0 || diagnostic != "" || !strings.Contains(flat, want) {
			t.Fatal("sparse human report lost size/savings qualification", want, code, human, diagnostic)
		}
	}
	code, human, diagnostic = f.run(context.Background(), "hashes", "--groups")
	flat = strings.Join(strings.Fields(human), " ")
	for _, want := range []string{"Logical size per file", "observations need not be simultaneous", "do not prove current duplicate files or safe cleanup", "no keeper or reclaimable-space estimate is provided"} {
		if code != 0 || diagnostic != "" || !strings.Contains(flat, want) {
			t.Fatal("sparse matching report claimed physical savings or current equality", want, code, human, diagnostic)
		}
	}
}

func TestDuplicateGateCLIRealHardlinkAliasRefusesKeeperAuthority(t *testing.T) {
	equal := bytes.Repeat([]byte("independent generated hardlink content\n"), 13)
	near := bytes.Clone(equal)
	near[len(near)/2] ^= 1
	names := []string{"original object", "alias path", "distinct copy", "near miss"}
	var originalStat, aliasStat unix.Stat_t
	f, p := duplicateGateFixture(t, names, func(parent string) {
		duplicateGateWrite(t, parent, names[0], equal)
		if err := os.Link(filepath.Join(parent, names[0]), filepath.Join(parent, names[1])); err != nil {
			t.Fatal(err)
		}
		duplicateGateWrite(t, parent, names[2], equal)
		duplicateGateWrite(t, parent, names[3], near)
		if err := unix.Stat(filepath.Join(parent, names[0]), &originalStat); err != nil {
			t.Fatal(err)
		}
		if err := unix.Stat(filepath.Join(parent, names[1]), &aliasStat); err != nil {
			t.Fatal(err)
		}
		if originalStat.Dev != aliasStat.Dev || originalStat.Ino != aliasStat.Ino || originalStat.Nlink != 2 || aliasStat.Nlink != 2 {
			t.Fatal("fixture did not create a real two-path hardlink")
		}
	})
	band := f.page.Bands[0]
	if band.KnownObjects != 3 || band.RepeatedSavedObjects != 1 || band.ConflictingIdentities != 0 || p.Targets[0].File.Device != p.Targets[1].File.Device || p.Targets[0].File.Inode != p.Targets[1].File.Inode {
		t.Fatal("same-size metadata did not preserve the actual alias", band)
	}
	_, originalRaw, groups, groupsRaw := duplicateGateOriginalHashes(t, f, p, [][]byte{equal, equal, equal, near})
	if len(groups.Groups) != 1 || groups.UnmatchedCompletedObservations != 1 {
		t.Fatal("real hardlink fixture did not form expected historical group", groupsRaw)
	}
	g := groups.Groups[0]
	if g.SavedIdentities != 2 || g.RepeatedSavedPaths != 1 || g.ConflictingSavedIdentities != 0 || len(g.Members) != 3 || g.SHA256 != fmt.Sprintf("%x", sha256.Sum256(equal)) {
		t.Fatal("historical group treated alias paths as independent saved objects", groupsRaw)
	}
	for i, member := range g.Members {
		if member.WorkID != strconv.Itoa(i+1) || member.RepeatedSavedIdentity != (i < 2) || member.SavedIdentityConflict {
			t.Fatal("whole-selection identity qualification differs from real hardlink", member)
		}
	}
	before := hashCLIBytes(t, f.base, f.root)
	// The other alias is intentionally omitted from the explicit role subset.
	// Whole-selection ambiguity must still block this requested member.
	code, raw, diagnostic := f.run(context.Background(), "hashes", "--preview", p.SelectionID, "--keeper", "3", "1", "--json")
	hashKeeperCLIError(t, code, raw, diagnostic, "hash_preview_identity_ambiguous", 1)
	code, raw, diagnostic = f.run(context.Background(), "hash", "--save-choice", p.SelectionID, "--keeper", "3", "1", "--json")
	hashChoiceCLIError(t, code, raw, diagnostic, "hash", "hash_preview_identity_ambiguous", 1)
	if !reflect.DeepEqual(before, hashCLIBytes(t, f.base, f.root)) || len(hashChoiceIDs(t, f.base)) != 0 || len(hashFreshJobCLIIDs(t, f.base)) != 0 {
		t.Fatal("ambiguous alias created authority, choice/job records or changed source bytes")
	}
	for _, report := range []struct {
		args []string
		want string
	}{{[]string{"hashes", "--json"}, originalRaw}, {[]string{"hashes", "--groups", "--json"}, groupsRaw}} {
		code, raw, diagnostic = f.run(context.Background(), report.args...)
		if code != 0 || diagnostic != "" || raw != report.want {
			t.Fatal("alias refusal changed original evidence or budget", code, raw, diagnostic)
		}
	}
	code, human, diagnostic := f.run(context.Background(), "hashes", "--groups")
	flat := strings.Join(strings.Fields(human), " ")
	for _, want := range []string{"Repeated paths in group 1", "This recorded identity appears in another selected path", "Saved identities do not establish inode continuity or independent storage", "no keeper or reclaimable-space estimate is provided"} {
		if code != 0 || diagnostic != "" || !strings.Contains(flat, want) {
			t.Fatal("hardlink human report hid alias or claimed independent storage", want, code, human, diagnostic)
		}
	}
}
