package inventory

import (
	"bytes"
	"context"
	"crypto/sha256"
	"database/sql"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"
	"time"
)

// Every saved input in these tests is generated by real scan/hash/choice/job
// APIs. Classifier-only differing inputs below are explicitly labelled and
// never written to storage or represented as genuine observed source changes.
func freshComparisonSaved(t *testing.T, s *HashStore, id string) SavedFreshJob {
	t.Helper()
	job, err := s.FreshJob(context.Background(), id)
	if err != nil || job.Comparison == nil {
		t.Fatal("saved exact job lacks its derived comparison", job, err)
	}
	freshComparisonClaims(t, *job.Comparison)
	return job
}

func freshComparisonClaims(t *testing.T, r HashFreshJobComparisonReport) {
	t.Helper()
	if r.Contract != HashFreshJobComparisonContract || r.Source != "saved_fresh_job_observations" || r.HashContract != FileHashContract || r.Scope != "exact_saved_fresh_job" || r.CurrentReadPermissionEvaluated || r.ApprovalAvailable || r.ProvenanceVerified || r.ContentVerified || r.CurrentStateVerified || r.DuplicatesVerified || r.Executable || r.EstimatedReclaimableBytes != nil {
		t.Fatal("fresh comparison claimed current equality, read permission, savings or cleanup", r)
	}
	if r.MatchingCopies+r.DifferingCopies+r.IncompleteCopies+r.BlockedCopies != len(r.Copies) {
		t.Fatal("comparison counts lost an explicit copy relation", r)
	}
}

func freshComparisonExactMembers(t *testing.T, job SavedFreshJob) {
	t.Helper()
	r := job.Comparison
	q := job.Record.Request
	if r == nil || r.JobID != job.ID || r.JobKey != job.Record.JobKey || r.RequestID != q.RequestID || r.ChoiceID != q.ChoiceID || r.StoreID != q.StoreID || r.SelectionID != q.SelectionID || r.InventoryID != q.InventoryID || len(r.Copies) != len(job.Work)-1 || r.ProgressInitialized != (len(job.Progress) != 0) {
		t.Fatal("comparison lost exact immutable job scope", r, job.Work)
	}
	members := []HashFreshJobComparisonMember{r.Keeper}
	for _, pair := range r.Copies {
		members = append(members, pair.Copy)
	}
	for i, member := range members {
		seed, target := job.Work[i], q.Targets[i]
		if member.Ordinal != i+1 || member.HistoricalWorkID != seed.HistoricalWorkID || member.Role != seed.Role || member.FileID != target.Target.File.ID || member.RootID != target.Target.File.RootID || !bytes.Equal(member.PathBytes, target.Target.File.PathBytes) || member.TargetDigest != seed.TargetDigest {
			t.Fatal("comparison remapped nonfirst keeper, ordered copies or frozen raw paths", member, target)
		}
		if len(job.Progress) == 0 {
			if member.Observation != nil {
				t.Fatal("untouched seed fabricated a fresh observation", member)
			}
		} else if member.Observation == nil || !reflect.DeepEqual(*member.Observation, job.Progress[i]) {
			t.Fatal("comparison refreshed, filtered or lost individual fresh evidence", member, job.Progress[i])
		}
	}
}

func freshComparisonComplete(t *testing.T, f *freshRunFixture, w *HashStore) SavedFreshJob {
	t.Helper()
	for range len(f.fresh.job.Work) {
		r, err := w.RunFreshConsented(context.Background(), f.consent.ID, f.fresh.m.f.scanner)
		if err != nil || r.Status != "hash_observed" || r.Progress.SHA256 != fmt.Sprintf("%x", sha256.Sum256(fullHashContents(65))) {
			t.Fatal("generated comparison setup lacks independently known completed hashes", r, err)
		}
	}
	return freshComparisonSaved(t, w, f.fresh.job.ID)
}

func TestHashFreshComparisonExactSeedsOrderAndCompletedHistoricalMatches(t *testing.T) {
	f := freshRunFiles(t, 65, 4, "3", "2", "1")
	w := f.fresh.m.f.store
	seed := freshComparisonSaved(t, w, f.fresh.job.ID)
	freshComparisonExactMembers(t, seed)
	if seed.Comparison.Status != "incomplete" || seed.Comparison.ProgressInitialized || seed.Comparison.IncompleteCopies != 2 || seed.Comparison.Keeper.HistoricalWorkID != "3" || seed.Comparison.Copies[0].Copy.HistoricalWorkID != "2" || seed.Comparison.Copies[1].Copy.HistoricalWorkID != "1" {
		t.Fatal("untouched exact subset imported original complete hashes", seed.Comparison)
	}
	w = f.open(t)
	initial := freshComparisonSaved(t, w, f.fresh.job.ID)
	freshComparisonExactMembers(t, initial)
	if !initial.Comparison.ProgressInitialized || initial.Comparison.Status != "incomplete" || initial.Comparison.Keeper.Observation == nil || initial.Comparison.Keeper.Observation.Status != "pending" || initial.Comparison.Keeper.Observation.SHA256 != "" {
		t.Fatal("initialization fabricated completed fresh content", initial.Comparison)
	}
	for i := range 3 {
		r, err := w.RunFreshConsented(context.Background(), f.consent.ID, f.fresh.m.f.scanner)
		if err != nil || r.Status != "hash_observed" || r.Ordinal != i+1 {
			t.Fatal(r, err)
		}
		job := freshComparisonSaved(t, w, f.fresh.job.ID)
		freshComparisonExactMembers(t, job)
		wantStatus := "incomplete"
		if i == 2 {
			wantStatus = "historical_hashes_match"
		}
		if job.Comparison.Status != wantStatus || job.Comparison.MatchingCopies != i || job.Comparison.IncompleteCopies != 2-i || job.Comparison.BlockedCopies != 0 || job.Comparison.DifferingCopies != 0 {
			t.Fatal("comparison inferred unsaved copies or lost every pair", job.Comparison)
		}
		for j, pair := range job.Comparison.Copies {
			want := "incomplete"
			if j < i {
				want = "historical_hashes_match"
			}
			if pair.Relation != want {
				t.Fatal("copy relation differs from genuine completion", j, pair)
			}
		}
		f.checkOriginal(t, w)
	}
	complete := freshComparisonSaved(t, w, f.fresh.job.ID)
	for _, pair := range complete.Comparison.Copies {
		if pair.Copy.Observation.CheckedAt.IsZero() || pair.Copy.Observation.SHA256 != fmt.Sprintf("%x", sha256.Sum256(fullHashContents(65))) || pair.Copy.Observation.LatestAttempt == nil || pair.Copy.Observation.LatestAttempt.Status != "settled" {
			t.Fatal("positive historical relation lacks individual settled observation", pair)
		}
	}
}

func TestHashFreshComparisonPartialAndKnownCanceledAttemptsStayIncomplete(t *testing.T) {
	f := freshRunFiles(t, int(FileHashStepByteLimit)+65, 2, "2", "1")
	w := f.open(t)
	r, err := w.RunFreshConsented(context.Background(), f.consent.ID, f.fresh.m.f.scanner)
	if err != nil || r.DurableOffset != FileHashStepByteLimit || r.Progress.SHA256 != "" {
		t.Fatal(r, err)
	}
	partial := freshComparisonSaved(t, w, f.fresh.job.ID)
	freshComparisonExactMembers(t, partial)
	if partial.Comparison.Status != "incomplete" || partial.Comparison.MatchingCopies != 0 || partial.Comparison.Keeper.Observation.DurableOffset != FileHashStepByteLimit || partial.Comparison.Keeper.Observation.SHA256 != "" {
		t.Fatal("partial fresh prefix was classified as a full historical hash", partial.Comparison)
	}
	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()
	r, err = w.runFreshConsented(ctx, f.consent.ID, f.fresh.m.f.scanner, hashFreshRunHooks{file: fileHashHooks{afterRead: func(int) { cancel() }}})
	if !errors.Is(err, context.Canceled) || r.Ordinal != 2 || r.Progress.SHA256 != "" || r.Usage.ReadBytes == 0 {
		t.Fatal(r, err)
	}
	canceled := freshComparisonSaved(t, w, f.fresh.job.ID)
	obs := canceled.Comparison.Copies[0].Copy.Observation
	if canceled.Comparison.Status != "incomplete" || canceled.Comparison.Copies[0].Relation != "incomplete" || obs.Status != "pending" || obs.DurableOffset != 0 || obs.SHA256 != "" || obs.LatestAttempt == nil || obs.LatestAttempt.Status != "settled" || obs.LatestAttempt.ReadBytes == nil || *obs.LatestAttempt.ReadBytes != r.Usage.ReadBytes {
		t.Fatal("known canceled usage inferred a digest or hid actual accounting", canceled.Comparison)
	}
	f.checkOriginal(t, w)
}

func TestHashFreshComparisonRunningAndRecoveredUnknownDoNotInferObservations(t *testing.T) {
	f := freshRunFiles(t, 65, 2, "2", "1")
	w := f.open(t)
	r, err := w.runFreshConsented(context.Background(), f.consent.ID, f.fresh.m.f.scanner, hashFreshRunHooks{settleCommit: func(*sql.Tx) error { return errors.New("generated unavailable settlement reply") }})
	if !errors.Is(err, ErrHashRecoveryRequired) || r.Usage.ReadBytes != 65 || r.Progress.SHA256 != "" {
		t.Fatal(r, err)
	}
	running := freshComparisonSaved(t, w, f.fresh.job.ID)
	obs := running.Comparison.Keeper.Observation
	if running.Comparison.Status != "incomplete" || obs.Status != "running" || obs.SHA256 != "" || obs.LatestAttempt == nil || obs.LatestAttempt.Status != "reserved" || obs.LatestAttempt.ReadBytes != nil || obs.LatestAttempt.RequestedBytes != nil || obs.LatestAttempt.ElapsedNS != nil {
		t.Fatal("saved running record inferred activity, known zero usage or a digest", running.Comparison)
	}
	reader, err := OpenHashReader(context.Background(), f.fresh.m.f.base)
	if err != nil {
		t.Fatal(err)
	}
	if saved := freshComparisonSaved(t, reader, f.fresh.job.ID); !reflect.DeepEqual(saved, running) {
		t.Fatal("saved-only reader recovered running comparison", saved)
	}
	if err = reader.Close(); err != nil {
		t.Fatal(err)
	}
	w = f.open(t) // Only this explicit exact-job writer recovers the attempt.
	unknown := freshComparisonSaved(t, w, f.fresh.job.ID)
	freshComparisonExactMembers(t, unknown)
	obs = unknown.Comparison.Keeper.Observation
	if unknown.Comparison.Status != "incomplete" || obs.Status != "pending" || obs.Sequence != 1 || obs.SHA256 != "" || obs.LatestAttempt.Status != "interrupted_unknown" || obs.LatestAttempt.ReadBytes != nil || obs.LatestAttempt.RequestedBytes != nil || obs.LatestAttempt.ElapsedNS != nil || unknown.FreshReadBytes != 0 || unknown.FreshReservedBytes != 65 || unknown.FreshBudget.TotalUnknownReservedBytes != 65 {
		t.Fatal("unknown usage became a positive historical relation or zero known read", unknown.Comparison)
	}
	f.checkOriginal(t, w)
}

func TestHashFreshComparisonChangedRealSourceBlocksInsteadOfReportingDifferentHash(t *testing.T) {
	f := freshRunFiles(t, 65, 3, "3", "1", "2")
	w := f.open(t)
	if r, err := w.RunFreshConsented(context.Background(), f.consent.ID, f.fresh.m.f.scanner); err != nil || r.Ordinal != 1 || r.Status != "hash_observed" {
		t.Fatal(r, err)
	}
	path := string(f.fresh.job.Record.Request.Targets[1].Target.File.PathBytes)
	stamp, err := os.Stat(path)
	if err != nil {
		t.Fatal(err)
	}
	changed := fullHashContents(65)
	changed[31] ^= 1
	if err = os.WriteFile(path, changed, 0600); err != nil {
		t.Fatal(err)
	}
	if err = os.Chtimes(path, stamp.ModTime(), stamp.ModTime()); err != nil {
		t.Fatal(err)
	}
	r, err := w.RunFreshConsented(context.Background(), f.consent.ID, f.fresh.m.f.scanner)
	if err == nil || r.Ordinal != 2 || r.Usage.ReadBytes != 0 || r.Progress.SHA256 != "" {
		t.Fatal("changed source produced an observed mismatch", r, err)
	}
	job := freshComparisonSaved(t, w, f.fresh.job.ID)
	freshComparisonExactMembers(t, job)
	if job.Comparison.Status != "blocked" || job.Comparison.BlockedCopies != 1 || job.Comparison.IncompleteCopies != 1 || job.Comparison.DifferingCopies != 0 || job.Comparison.MatchingCopies != 0 || job.Comparison.Copies[0].Relation != "blocked" || job.Comparison.Copies[1].Relation != "incomplete" || job.Comparison.Copies[0].Copy.Observation.Status != "invalidated" || job.Comparison.Copies[0].Copy.Observation.SHA256 != "" {
		t.Fatal("live change was reported as a fresh differing hash or masked by incomplete work", job.Comparison)
	}
	f.checkOriginal(t, w)
}

func freshComparisonCloneShape(t *testing.T, job SavedFreshJob) SavedFreshJob {
	t.Helper()
	body, err := json.Marshal(job)
	if err != nil {
		t.Fatal(err)
	}
	var copy SavedFreshJob
	if err = json.Unmarshal(body, &copy); err != nil {
		t.Fatal(err)
	}
	copy.Comparison = nil
	return copy
}

func TestHashFreshComparisonClassifierOnlyShapesKeepEveryMixedRelation(t *testing.T) {
	f := freshRunFiles(t, 65, 4, "3", "2", "1")
	w := f.open(t)
	complete := freshComparisonComplete(t, f, w)
	equal := fullHashContents(65)
	different := bytes.Clone(equal)
	different[17] ^= 1
	differSHA := fmt.Sprintf("%x", sha256.Sum256(different))
	// These are classifier-only, validated-shape fixtures. No altered SHA or
	// lifecycle state is persisted. A real changed file blocks as tested above.
	cases := []struct {
		name      string
		mutate    func(*SavedFreshJob)
		status    string
		relations []string
		counts    [4]int
	}{
		{"matching", func(*SavedFreshJob) {}, "historical_hashes_match", []string{"historical_hashes_match", "historical_hashes_match"}, [4]int{2, 0, 0, 0}},
		{"one_differing", func(j *SavedFreshJob) { j.Progress[1].SHA256 = differSHA }, "historical_hashes_differ", []string{"historical_hashes_differ", "historical_hashes_match"}, [4]int{1, 1, 0, 0}},
		{"all_differing", func(j *SavedFreshJob) { j.Progress[1].SHA256 = differSHA; j.Progress[2].SHA256 = differSHA }, "historical_hashes_differ", []string{"historical_hashes_differ", "historical_hashes_differ"}, [4]int{0, 2, 0, 0}},
		{"incomplete_before_differing", func(j *SavedFreshJob) {
			j.Progress[1].SHA256 = differSHA
			j.Progress[2].Status = "pending"
			j.Progress[2].SHA256 = ""
			j.Progress[2].DurableOffset = 0
			j.Progress[2].CheckedAt = time.Time{}
		}, "incomplete", []string{"historical_hashes_differ", "incomplete"}, [4]int{0, 1, 1, 0}},
		{"blocked_before_differing", func(j *SavedFreshJob) {
			j.Progress[1].SHA256 = differSHA
			j.Progress[2].Status = "invalidated"
			j.Progress[2].Code = "file_changed"
			j.Progress[2].SHA256 = ""
			j.Progress[2].DurableOffset = 0
			j.Progress[2].CheckedAt = time.Time{}
		}, "blocked", []string{"historical_hashes_differ", "blocked"}, [4]int{0, 1, 0, 1}},
		{"keeper_blocked", func(j *SavedFreshJob) {
			j.Progress[0].Status = "invalidated"
			j.Progress[0].Code = "file_changed"
			j.Progress[0].SHA256 = ""
			j.Progress[0].DurableOffset = 0
			j.Progress[0].CheckedAt = time.Time{}
		}, "blocked", []string{"blocked", "blocked"}, [4]int{0, 0, 0, 2}},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			input := freshComparisonCloneShape(t, complete)
			tc.mutate(&input)
			before := freshComparisonCloneShape(t, input)
			r, err := compareFreshJob(input)
			if err != nil {
				t.Fatal("classifier refused a labelled internally shaped fixture", r, err)
			}
			freshComparisonClaims(t, r)
			if r.Status != tc.status || [4]int{r.MatchingCopies, r.DifferingCopies, r.IncompleteCopies, r.BlockedCopies} != tc.counts || len(r.Copies) != 2 {
				t.Fatal("mixed aggregate lost pair evidence or precedence", r)
			}
			for i, relation := range tc.relations {
				if r.Copies[i].Relation != relation || r.Copies[i].Copy.HistoricalWorkID != []string{"2", "1"}[i] {
					t.Fatal("classifier reordered or omitted a copy", r.Copies)
				}
			}
			if !reflect.DeepEqual(input, before) {
				t.Fatal("classifier mutated its validated-shape input")
			}
		})
	}
	// Corrupt shapes are errors, not an ordinary incomplete/blocked relation.
	for name, mutate := range map[string]func(*SavedFreshJob){
		"wrong_job_id":         func(j *SavedFreshJob) { j.ID = "not a full job ID" },
		"target_binding":       func(j *SavedFreshJob) { j.Work[1].TargetDigest = strings.Repeat("0", 64) },
		"copy_order":           func(j *SavedFreshJob) { j.Progress[1], j.Progress[2] = j.Progress[2], j.Progress[1] },
		"partial_progress_set": func(j *SavedFreshJob) { j.Progress = j.Progress[:2] },
		"path_redirect":        func(j *SavedFreshJob) { j.Progress[1].PathBytes = []byte("/generated/other") },
		"unfinished_digest":    func(j *SavedFreshJob) { j.Progress[1].Status = "pending" },
		"complete_unknown_attempt": func(j *SavedFreshJob) {
			j.Progress[1].LatestAttempt.Status = "interrupted_unknown"
			j.Progress[1].LatestAttempt.ReadBytes = nil
			j.Progress[1].LatestAttempt.RequestedBytes = nil
			j.Progress[1].LatestAttempt.ElapsedNS = nil
		},
	} {
		t.Run("corrupt_shape_"+name, func(t *testing.T) {
			input := freshComparisonCloneShape(t, complete)
			mutate(&input)
			r, err := compareFreshJob(input)
			if !errors.Is(err, ErrHashFreshProgressCorrupt) || !reflect.DeepEqual(r, HashFreshJobComparisonReport{}) {
				t.Fatal("malformed shape exposed partial positive/blocked comparison", r, err)
			}
		})
	}
	if saved := freshComparisonSaved(t, w, f.fresh.job.ID); !reflect.DeepEqual(saved, complete) {
		t.Fatal("classifier fixture leaked altered evidence into saved state", saved)
	}
}

func freshComparisonStoredBytes(t *testing.T, root string) map[string][32]byte {
	t.Helper()
	result := map[string][32]byte{}
	err := filepath.WalkDir(root, func(path string, entry os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if entry.IsDir() || strings.HasSuffix(path, "-shm") || strings.HasSuffix(path, "writer.lock") {
			return nil
		}
		body, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		if len(body) == 0 && strings.HasSuffix(path, "-wal") {
			return nil
		}
		result[path] = sha256.Sum256(body)
		return nil
	})
	if err != nil {
		t.Fatal(err)
	}
	return result
}

func TestHashFreshComparisonClonesNestedEvidenceAndReadsOfflineWithoutClockOrRecovery(t *testing.T) {
	f := freshRunFiles(t, 65, 4, "3", "2", "1")
	w := f.open(t)
	complete := freshComparisonComplete(t, f, w)
	// Each report/member/observation path and usage pointer is independently
	// owned; mutating one cannot mutate sibling evidence or saved progress.
	mutated := freshComparisonSaved(t, w, f.fresh.job.ID)
	mutated.Comparison.Keeper.PathBytes[0] ^= 1
	if !bytes.Equal(mutated.Progress[0].PathBytes, complete.Progress[0].PathBytes) || !bytes.Equal(mutated.Comparison.Keeper.Observation.PathBytes, complete.Progress[0].PathBytes) {
		t.Fatal("member path aliases progress or observation path")
	}
	mutated.Comparison.Keeper.Observation.PathBytes[0] ^= 1
	*mutated.Comparison.Keeper.Observation.LatestAttempt.ReadBytes = -1
	*mutated.Comparison.Keeper.Observation.LatestAttempt.RequestedBytes = -1
	*mutated.Comparison.Keeper.Observation.LatestAttempt.ElapsedNS = -1
	mutated.Comparison.Copies[0].Copy.PathBytes[0] ^= 1
	*mutated.Comparison.Copies[0].Copy.Observation.LatestAttempt.ReadBytes = -1
	if !reflect.DeepEqual(mutated.Progress, complete.Progress) || !reflect.DeepEqual(mutated.Comparison.Copies[1], complete.Comparison.Copies[1]) {
		t.Fatal("nested comparison buffers or usage pointers alias saved progress/sibling evidence")
	}
	if saved := freshComparisonSaved(t, w, f.fresh.job.ID); !reflect.DeepEqual(saved, complete) {
		t.Fatal("caller mutation redirected or corrupted saved comparison", saved)
	}
	w.now = func() time.Time { return f.consent.Approval.ExpiresAt.Add(time.Hour) }
	if _, err := w.RevokeFreshRead(context.Background(), f.consent.ID); err != nil {
		t.Fatal(err)
	}
	prior := freshComparisonSaved(t, w, f.fresh.job.ID)
	if !reflect.DeepEqual(prior.Comparison, complete.Comparison) || prior.ReadConsent.Status != "revoked" {
		t.Fatal("saved consent refreshed historical comparison", prior)
	}
	if err := f.fresh.m.f.source.Close(); err != nil {
		t.Fatal(err)
	}
	f.fresh.m.f.scanner.Close()
	for _, path := range []string{f.fresh.m.f.root, f.fresh.m.f.stateDir} {
		if err := os.Rename(path, path+".offline"); err != nil {
			t.Fatal(err)
		}
	}
	if err := os.WriteFile(filepath.Join(f.fresh.m.f.base, "config.toml"), []byte("malformed [ TOML"), 0600); err != nil {
		t.Fatal(err)
	}
	w.now = func() time.Time { t.Fatal("saved-only comparison evaluated a clock"); return time.Time{} }
	before := freshComparisonStoredBytes(t, f.fresh.m.f.base)
	reader, err := OpenHashReader(context.Background(), f.fresh.m.f.base)
	if err != nil {
		t.Fatal("saved-only reader rejected a held writer lock", err)
	}
	defer reader.Close()
	reader.now = w.now
	for range 2 {
		shown := freshComparisonSaved(t, reader, f.fresh.job.ID)
		if !reflect.DeepEqual(shown, prior) || !reflect.DeepEqual(before, freshComparisonStoredBytes(t, f.fresh.m.f.base)) {
			t.Fatal("offline comparison changed records, consent, clock, usage or source state", shown)
		}
		f.checkOriginal(t, reader)
	}
}

func TestHashFreshComparisonCorruptionReturnsNoPartialSavedReport(t *testing.T) {
	for _, kind := range []string{"missing_progress", "checkpoint", "complete_unknown_usage"} {
		t.Run(kind, func(t *testing.T) {
			f := freshRunFiles(t, 65, 2, "2", "1")
			w := f.open(t)
			_ = freshComparisonComplete(t, f, w)
			var err error
			switch kind {
			case "missing_progress":
				if _, err = w.db.Exec("DROP TRIGGER hash_fresh_progress_no_delete"); err == nil {
					if _, err = w.db.Exec("DELETE FROM hash_fresh_attempt WHERE job_id=? AND ordinal=2", f.fresh.job.ID); err == nil {
						_, err = w.db.Exec("DELETE FROM hash_fresh_progress WHERE job_id=? AND ordinal=2", f.fresh.job.ID)
					}
				}
			case "checkpoint":
				if _, err = w.db.Exec("DROP TRIGGER hash_fresh_progress_monotonic"); err == nil {
					_, err = w.db.Exec("UPDATE hash_fresh_progress SET checkpoint=? WHERE job_id=? AND ordinal=2", []byte("not a saved checkpoint"), f.fresh.job.ID)
				}
			case "complete_unknown_usage":
				_, err = w.db.Exec("UPDATE hash_fresh_attempt SET status='interrupted_unknown',requested_bytes=NULL,read_bytes=NULL,elapsed_ns=NULL WHERE job_id=? AND ordinal=2", f.fresh.job.ID)
			}
			if err != nil {
				t.Fatal(err)
			}
			job, err := w.FreshJob(context.Background(), f.fresh.job.ID)
			if !errors.Is(err, ErrHashFreshProgressCorrupt) || job.ID != "" || job.Comparison != nil || len(job.Progress) != 0 {
				t.Fatal("corrupt evidence was downgraded to blocked/partial comparison", job, err)
			}
			f.checkOriginal(t, w)
		})
	}
}

func TestHashFreshComparisonCanceledReadsReturnNoPartialEvidence(t *testing.T) {
	f := freshRunFiles(t, 65, 2, "2", "1")
	w := f.open(t)
	prior := freshComparisonComplete(t, f, w)
	ctx, cancel := context.WithCancel(context.Background())
	cancel()
	job, err := w.FreshJob(ctx, f.fresh.job.ID)
	if !errors.Is(err, context.Canceled) || job.ID != "" || job.Comparison != nil {
		t.Fatal("pre-canceled report returned partial comparison", job, err)
	}
	w.mu.Lock()
	func() {
		defer w.mu.Unlock()
		ctx, cancel := context.WithTimeout(context.Background(), 20*time.Millisecond)
		defer cancel()
		job, err = w.FreshJob(ctx, f.fresh.job.ID)
		if !errors.Is(err, context.DeadlineExceeded) || job.ID != "" || job.Comparison != nil {
			t.Fatal("canceled gate waiter returned historical result without completing a snapshot", job, err)
		}
	}()
	if shown := freshComparisonSaved(t, w, f.fresh.job.ID); !reflect.DeepEqual(shown, prior) {
		t.Fatal("canceled saved-only report changed genuine comparison", shown)
	}
	f.checkOriginal(t, w)
}
